### ISSUE TITLE
帮帮忙

### ISSUE THREAD

**Issue by hongqimei** [ML-Song/Smoke-Detection#9]
Using TensorFlow backend.
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-a708f6c2f11f>", line 1, in <module>
    runfile('C:/Projects/Python/DeepLearning/smoke_detection/python_files/Smoke_Detection_VGG16_with_SVM_and_Fully_Connected_Network.py', wdir='C:/Projects/Python/DeepLearning/smoke_detection/python_files')
  File "C:\Program Files\JetBrains\PyCharm 2019.3.3\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.3.3\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Projects/Python/DeepLearning/smoke_detection/python_files/Smoke_Detection_VGG16_with_SVM_and_Fully_Connected_Network.py", line 72, in <module>
    training_set_vgg16_features.append(model_vgg16.predict(x).reshape((7*7*512, )))# 计算该张图片的特征
ValueError: cannot reshape array of size 50176 into shape (25088,)

**Comment by bao-O** [comment]
@hongqimei  Can you share me smoke dataset via google drive or other platform? I couldn't download it for some reasons.
